name: Testing Pipeline
run-name: Started Testing after Action from @${{ github.actor }}
on: 
  push:
  workflow_dispatch:
permissions: write-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Installs
      run: |
        npm install
    - name: Run TESTS
      run: npm run test
